let item: number[] = []
AlphaBot2.SensorCalibrated()
let max = AlphaBot2.ReadSensorMin()
let min = AlphaBot2.ReadSensorMin()
serial.writeNumber(max[0])
serial.writeString(" ")
serial.writeNumber(max[1])
serial.writeString(" ")
serial.writeNumber(max[2])
serial.writeString(" ")
serial.writeNumber(max[3])
serial.writeString(" ")
serial.writeNumber(max[4])
serial.writeString(" ")
serial.writeNumber(min[0])
serial.writeString(" ")
serial.writeNumber(min[1])
serial.writeString(" ")
serial.writeNumber(min[2])
serial.writeString(" ")
serial.writeNumber(min[3])
serial.writeString(" ")
serial.writeNumber(min[4])
serial.writeString(" ")
basic.forever(function () {
    item = AlphaBot2.readCalibrated()
    serial.writeNumber(Math.round(item[0]))
    serial.writeString(" ")
    serial.writeNumber(Math.round(item[1]))
    serial.writeString(" ")
    serial.writeNumber(Math.round(item[2]))
    serial.writeString(" ")
    serial.writeNumber(Math.round(item[3]))
    serial.writeString(" ")
    serial.writeNumber(Math.round(item[4]))
    serial.writeLine("")
    basic.pause(500)
})
